### ISSUE TITLE
investigate the impact of changing account_id in targetAccountMappings

### ISSUE THREAD

**Issue by chamcca** [awslabs/seed-farmer#102]

**Comment by dgraeber** [comment]
With the addition of https://github.com/awslabs/seed-farmer/pull/204 - if you did change the account_id in the target mappings and tried to deploy, seedfarmer will stop as it triggers a destroy of modules that have dependencies (assuming the new target account has been bootstrapped).  You would have to explicitly delete all dependency modules.  This would mitigate an inadvertent change in mappings.
