### ISSUE TITLE
[BUG] seedfarmer apply doesn't set exit code >0 on failure 

### ISSUE THREAD

**Issue by AndyEfaa** [awslabs/seed-farmer#147]
**Describe the bug**

**To Reproduce**
1. Start `seedfarmer apply` command with a deployment file that contains a known error.
2. Wait for command to fail.
3. The execution will be logged as successful. The CLI will not receive a exit code >0 on failure. 

**Expected behavior**
If seedfarmer apply fails, I would expect a exit code >0 on failure

**Screenshots**
N/A

**Comment by dgraeber** [comment]
Looks like if one module fails in the group, we are detecting it, but exiting with a status code of 0....will change to a different status code

**Comment by dgraeber** [comment]
Fix merged and will be in next patch release
