### ISSUE TITLE
[BUG] Typo when running deployment dry run

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#152]
**Describe the bug**
Small typo when running deployment

**To Reproduce**
1. Run seedfarmer apply <path_to_deployment.yaml>  --dry-run
2. Look at the output table header reads "Deployemnt" instead of "Deployment"

**Screenshots**
<img width="834" alt="image" src="https://user-images.githubusercontent.com/85226895/196156789-532034df-2e41-489f-bc3c-8f32a122fb6b.png">

**Comment by dgraeber** [comment]
Corrected and merged.  Will be in the next patch release
