### ISSUE TITLE
[BUG] Seedfarmer apply fails when using --project name different than addf during bootstrapping

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#153]
**Describe the bug**
After running seedfarmer bootstrapping with a specific `--project`, the appropriate CF and Role for the tooling account get's created. However, when running seedfarmer apply, the command attempts to assume a role with `addf` in it's name instead of the expected project name. 

**To Reproduce**
1. Clone project
2. Run bootstrapping 
-  `seedfarmer bootstrap toolchain --project foo --as-target --trusted-principal arn:aws:iam::XXX:role/Admin`
4. Wait for bootstrapping to complete successfully
5. Check IAM for the created role `arn:aws:iam::XXX:role/seedfarmer-foo-toolchain-role`
6. Deploy a manifest
- `seedfarmer apply manifests/shared-infra/deployment.yaml`
7. Deployment fails with error

```bash
  File "session_manager.py", line 142, in _check_for_toolchain
    session, role = self._get_toolchain()
  File "session_manager.py", line 154, in _get_toolchain
    toolchain_role = user_client.assume_role(
  File "/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::XXX:assumed-role/MyRole/user-1 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::XXX:role/seedfarmer-addf-toolchain-role
```

The apply command attempts to use `arn:aws:iam::XXX:role/seedfarmer-addf-toolchain-role` when the correct role is `arn:aws:iam::XXX:role/seedfarmer-foo-toolchain-role`

**Expected behavior**
Use the toolchain role created during bootstrapping `arn:aws:iam::XXX:role/seedfarmer-foo-toolchain-role`

**Comment by dgraeber** [comment]
This is not a bug.  The project name for all addf modules is `addf`.  All the modules for `addf` can only run in a project named `addf`.  You can change the `deployment` name to have unique environments. but the project for these modules must be `addf`.

Please contact me regarding what you are trying to do and I can elaborate.
