### ISSUE TITLE
[FEATURE] Throw Error on intra-group dependency

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#178]
**Is your feature request related to a problem? Please describe.**
When deploying two modules in the same group that depend on each other the module deployments still execute in parallel. The expectation is that there is no intra-group dependencies, only inter-group dependencies.

Throw an exception when intra-group dependencies are detected to warn users about the race condition for deployment that could cause issues. 

**Describe the solution you'd like**
Exception is thrown when intra-group `valueFrom.moduleMetadata` dependencies are detected. Link to documentation on how dependencies are resolved in the error output.

**Comment by zaremb** [comment]
I have faced the same issue. I was not aware that intra-group dependencies are not supported
