### ISSUE TITLE
[BUG] seedfarmer remove moduledata does not remove entries from SSM Parameter Store

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#180]
**Describe the bug**
When running `seedfarmer remove moduledata -d <deployment> -g <group> -m <module>` the command exits successfully but with no output. When checking SSM Parameter store the moduledata is still there.

**To Reproduce**
1. Deploy a test deployment/group/module
2. Run `seedfarmer remove moduledata -d <deployment> -g <group> -m <module>`
3. Check SSM parameter store and search for <module>

**Expected behavior**
There should be no entries for the moduledata

**Comment by dgraeber** [comment]
This is not a bug.  Removing `moduledata` is an unrecoverable event.  The ability to remove module data via CLI is reserved for the deployment-role when running inside of codeseeder (and thus is aware of its account and region).  But, if an end user is really determined, the can invoke this CLI function if they also pass in the target_account_id and the region where the moduledata resides to force a delete.  This is to prevent and inadvertent deletions.

If you feel this needs to be changed, please issue a feature request with the appropriate reasoning and we can evaluate.

**Comment by a13zen** [comment]
The output from the cli doesn't make any of the above very clear. It is actually quite common for the need to delete moduledata during module development. If modules are moved between groups, or have errors in their deployspecs or have parameters that are modified, all of these result in errors that make deployments completely impossible without removing the moduledata. 

Can't moduledata always be regenerated (and corrected?) on rerunning `apply`?
