### ISSUE TITLE
[FEATURE] support ECR OCI images as source for modules

### ISSUE THREAD

**Issue by chamcca** [awslabs/seed-farmer#194]
**Is your feature request related to a problem? Please describe.**
Currently, source code for modules is either stored locally in the seed-farmer project or remotely in git repos. This doesn't provide a mechanism for distributing closed source modules.

**Describe the solution you'd like**
Enable pulling .tar.gz files from ECR that are stored as OCI images. The `path` attribute of the Module Manifest should support paths of the form `oci::public.ecr.aws/public-modules:v0.1.0//networking/`. Here, `oci::` informs us that the module source needs to be pulled from an ECR OCI repository. `public.ecr.aws/public-images:v0.1.0` is the repository URI including Tag. and the optional `//networking/` indicates that the module is loaded from the networking/ sub-directory of the extracted .tar.gz (enabling OCI images with multiple modules).

**Comment by dgraeber** [comment]
Closing for now...
