### ISSUE TITLE
[FEATURE] Add step by step guide to deploy a sample application using multiaccount architecture

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#238]
**Is your feature request related to a problem? Please describe.**
Recently I have bootstrapped accounts for multiaccount deployment. There is toolchain account + n target accounts. I have read the documentation on this, but nevertheless it required a lot of trial and error. This was mostly related to iam permissions/trust relationships, but also with how to handle manifests for different accounts (i.e. I was surprised to learn that region can not come from environment variable, but account can). Finally, I could not find any details how the ideal workflow would look like: should I have one manifest with reading account from env var, or there should be manifest for each stage?

**Describe the solution you'd like**
I would like to have a step by step guide how to bootstrap multiaccount (with code snippets), how to deploy multiaccount (i.e. toolchain, dev, prod) demo application, and how ideal workflow would look like.

**Comment by dgraeber** [comment]
Please see https://seed-farmer.readthedocs.io/en/latest/bootstrapping.html

@zaremb Can you elaborate on the trial and error?   Also, I don't understand the comment `manifest for each stage`....

**Comment by dgraeber** [comment]
Talking with @zaremb , we can add a `Quick Start` section to the Docs
