### ISSUE TITLE
[BUG] Typo in the table showing modules to be deployed

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#240]
**Describe the bug**
Table says "Deployemnt" instead of "Deployment"
<img width="615" alt="image" src="https://user-images.githubusercontent.com/18630245/219417404-0c5d40de-247b-47d5-9166-c3dba387faef.png">

**To Reproduce**
1. run seedfarmer apply on any working manifest

**Comment by dgraeber** [comment]
@zaremb I am not seeing this in the current codebase.  What is your seedfarmer version?   I think I corrected this earlier

**Comment by dgraeber** [comment]
This was corrected on https://github.com/awslabs/seed-farmer/pull/154

Please update your seedfarmer version to see
