### ISSUE TITLE
[FEATURE] Add support for custom images for Codebuild for execution 

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#242]
**Is your feature request related to a problem? Please describe.**
When running the build some application specific modules, they might require complex build environments e.g:
- Installing custom libraries or versions of frameworks
- Potentially containing code artifacts which are not available from within Codebuild (but might be from on-prem or a developer laptop)
- Include artifact build steps which take a very long time to run

For these cases it would make sense for us to package our dependencies into a Docker Image which would be used by seedfarmer/codeseeder 

**Describe the solution you'd like**
We would need:
1. A mechanism to specify a custom image uri for a module to use
2. This URI would need to be passed through seedfarmer -> codeseeder -> codebuild to tell it to use this image before executing the deployspec

There is a need for supporting custom images for Codebuild both on the global (all modules) or specific modules

**Comment by dgraeber** [comment]
@a13zen using the `deployspec.yaml` is not a viable option....we can support using a custom image, but not in that manner.  More to come...

**Comment by a13zen** [comment]
Nice! 💪
