### ISSUE TITLE
[FEATURE] Specify per-module prefix

### ISSUE THREAD

**Issue by PatWie** [awslabs/seed-farmer#248]
**Is your feature request related to a problem? Please describe.**
Assuming my project has the prefix `MY`.
Re-using modules from implementations like [ADDF](https://github.com/awslabs/autonomous-driving-data-framework) is a two step process:
1. copy over the implementation
2. replace the prefix ([example](https://github.com/awslabs/autonomous-driving-data-framework/blob/main/modules/core/aws-batch/app.py#L13)) to the one used by the current project, ie. replace all `ADDF` by `MY`

**Describe the solution you'd like**
Ideally, I would add that project as a git-submodule (eg. under `thirdparty/addf`) and refer to it as:

```yaml
name: task-a
path: thirdparty/addf/modules/core/aws-batch
prefix: addf
parameters:
....
```

and have seed-farmer substitute the prefix `ADDF` with the one from the current project (`MY`) in the passed-over/exported parameters.

**Describe alternatives you've considered**
Like described above currently, copying code is required with the additional step of renaming the prefix. Having the solution as described via a git-submodule would allow to provide bugfixes upstream ([example](https://github.com/awslabs/autonomous-driving-data-framework/pull/167)).

**Comment by dgraeber** [comment]
We are exploring a more effective solution to match this request.

**Comment by chamcca** [comment]
see: https://github.com/awslabs/seed-farmer/pull/249

**Comment by dgraeber** [comment]
The PR #249 provide in-depth explanations to accommodate this rquest.
