### ISSUE TITLE
[BUG] git link codecommit protocol looks suspicious

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#269]
**Describe the bug**
Using gitlink in manifest with git-remote-codecommit fails to clone due to 
```  File "/root/.pyenv/versions/3.7.6/lib/python3.7/site-packages/git/cmd.py", line 478, in check_unsafe_protocols
    f"The `{protocol}::` protocol looks suspicious, use `allow_unsafe_protocols=True` to allow it."
git.exc.UnsafeProtocolError: The `codecommit::` protocol looks suspicious, use `allow_unsafe_protocols=True` to allow it.
``` 
 

This was narrowed down by me to gitpython dependency of seedfarmer.
gitpython==3.1.29 <-- this works
gitpython==3.1.31 <-- this does not

**To Reproduce**
1. Install latest seedfarmer (in new environment, bug will not show up if you already have previous version of gitpython installed)
2. Use codecommit http(grc) git link in manifest, ( git::codecommit::[...])
3. Run seedfarmer apply

**Potential solution**
Allow using unsafe protocol if format matches codecommit grc

**Comment by zaremb** [comment]
Current workaround:
Manually install gitpython version 3.1.29 before running seedfarmer apply

**Comment by dgraeber** [comment]
I will look at both options.  Unless there is a reason to use the newer version of the library the least intrusive change would be to lock the version of gitpython to 3.1.29.  I will investigate

**Comment by dgraeber** [comment]
NOTE: that library is currently locked at "gitpython~=3.1.27"

**Comment by zaremb** [comment]
I would suggest to update the library and keep ~= to keep getting security patches. AFAIK, the current lock to ~=3.1.27 is matching versions as follow:
>= 3.1.27, == 3.1.*
Reference: https://peps.python.org/pep-0440/#compatible-release
