### ISSUE TITLE
[FEATURE] Support viewing & exporting manifest/group/module outputs

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#28]
**Is your feature request related to a problem? Please describe.**
When developing a module that depends on a different module for it's inputs, for instance an EC2 module that needs the VPC ID from the optional/networking module, it is hard to develop now knowing which outputs from the networking module have been created.

**Describe the solution you'd like**
Add CLI support for viewing the input/output values for an already deployed manifest. E.g.

`cli describe manifest/deployment.yaml`

Outputs all of the inputs/outputs of the already deployed modules for that manifest  (with actual resolved values)

`cli describe manifest/deployment.yaml --group foo`

Describes inputs/outputs of the already deployed group `foo` (with actual resolved values)

`cli describe manifest/deployment.yaml --group foo --module bar`

Describes inputs/ouputs of the already deployed module `bar` for group `foo` with the actual resolved values. 

BONUS Feature:

Additional command for exporting the values from module output into local environment variables

`cli describe manifest/deployment.yaml --group foo --module bar --export-local-env`

Shows and outputs the variables into my local environment variables. This was I can run `cdk synth` on the module under development and wire up it's dependencies as it will be available in CodeBuild. 

**Describe alternatives you've considered**

**Additional context**
When developing inter dependent modules, understanding the output of an already deployed module allows me to more easily design the inputs for the module under development.

**Comment by dgraeber** [comment]
We currently have the ability to list/display the module outputs:
`seedfarmer list moduledata -d <deployment> -g <group> -m <module> `

Please confirm this is what you need?
