### ISSUE TITLE
[FEATURE] Generate link to CodeBuild output on deployment failure

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#29]
**Is your feature request related to a problem? Please describe.**
When deploying and an error occurs and you'd like to view the logs (for instance when you forgot to run deploy with --debug), you need to navigate to CodeBuild in the console and find the correct build run. 

**Describe the solution you'd like**
When something goes wrong, generate a link in the console that can be opened in the browser that would jump directly to the codebuild build and logs.

**Comment by dgraeber** [comment]
We can look into this.  We just added the codebuild build id to the logging in codeseeder
