### ISSUE TITLE
[FEATURE]  Support for Providing Parameters Longer than 1000 Characters

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#301]
**Is your feature request related to a problem? Please describe.**
Codebuild has limitation of 1000 characters as env var. This poses a challenge when I need to pass complex and lengthy parameters, such as JSON configurations or other data, to  seedfarmer modules.

**Describe the solution you'd like**
I would like to request a feature that allows for providing parameter values longer than 1000 characters in Seedfarmer. One possible solution could be to support passing parameter values as files, similar to how artifacts can be passed as files in CodeBuild.

For example, if I have a JSON configuration with three degrees of depth, such as a phonebook with multiple contacts:
```
{
  "phonebook": {
    "contact1": {
      "name": "John Doe",
      "phone": "123-456-7890",
      "email": "johndoe@example.com",
      "address": "1234 Elm Street, Springfield, IL 62704"
    },
    "contact2": {
      "name": "Jane Smith",
      "phone": "987-654-3210",
      "email": "janesmith@example.com",
      "address": "5678 Oak Street, Shelbyville, IL 62565"
    },
    "contact3": {
      "name": "Mark Johnson",
      "phone": "555-123-4567",
      "email": "markjohnson@example.com",
      "address": "7890 Maple Street, Decatur, IL 62521"
    },
    "contact4": {
      "name": "Sarah Brown",
      "phone": "777-888-9999",
      "email": "sarahbrown@example.com",
      "address": "3456 Pine Street, Chatham, IL 62629"
    },
    "contact5": {
      "name": "Michael Davis",
      "phone": "111-222-3333",
      "email": "michaeldavis@example.com",
      "address": "5678 Cedar Street, Taylorville, IL 62568"
    },
    "contact6": {
      "name": "Emily Wilson",
      "phone": "444-555-6666",
      "email": "emilywilson@example.com",
      "address": "1234 Birch Street, Rochester, IL 62563"
    }
  }
}

```  

**Describe alternatives you've considered**
As an alternative, I have considered splitting the parameter values into multiple smaller environment variables, but this can quickly become cumbersome and hard to manage, especially for complex and lengthy parameter values.

**Additional context**
Link to relevant documentation:
https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CodeBuild.html#action-reference-CodeBuild-config

> When you enter the name, value, and type for your environment variables configuration, especially if the environment variable contains CodePipeline output variable syntax, do not exceed the 1000-character limit for the configuration’s value field. A validation error is returned when this limit is exceeded.

**Comment by dgraeber** [comment]
@zaremb I have been kicking around an idea of including a file or directory (that is co-located to the project parallel to `seedfarmer.yaml`) that will get included in the bundle sent to codebuild.  It will be apart of the checksum md5 calculation, so any changes to it will be detected.  It will be up to the person / process invoking the CLI to make sure the file is of the proper version / content etc on the filesystem and it configured in the module manifest.

I am looking to verbally kick the tires on this solution.  Let me know when I can run it past you to see if it meets your use case (other people have asked for symlinking...which we CANNOT support), but this design may meet all requests.

**Comment by zaremb** [comment]
I think that will work! Lets have a chat about this
