### ISSUE TITLE
[FEATURE] Implement dependency management between modules incase of module output / input change

### ISSUE THREAD

**Issue by AndyEfaa** [awslabs/seed-farmer#321]
**Scenario**: 
We do have a deployment map with 2 modules. The deployment order is as follows:
First Module A gets deployed, then module B gets deployed.

The CDK app in module A generates output X. 
The CDK app within module B takes output X as input. 

We then made a change to the CDK app in Module A that lead to an output change in X. 
The CDK app within module B wasn't changed.

**Current behavior:** 
Module B doesn't get triggered for (re)deployment, despite it's input variable being changed.

**Expected behavior:**
Module B gets automatically (re-)deployed, since it's input changed.

**Comment by dgraeber** [comment]
@AndyEfaa Currently we do not force redeployment of downstream modules when an upstream module has changed.  We can evaluate the feasibility of such a solution.
