### ISSUE TITLE
[FEATURE] Provide CodeBuild Job Links in seedfarmer apply Debug Mode at the Start of Deployment

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#325]
**Is your feature request related to a problem? Please describe.**
When running seedfarmer apply in debug mode, the CodeBuild job link is currently only provided after a job fails. This delay in providing the link hampers the troubleshooting and review process for module deployments.

**Describe the solution you'd like**
I would like the seedfarmer apply command in debug mode to consistently provide the CodeBuild job link for each module deployment, regardless of the job's outcome. Ideally, the link should be included in the output from the start, enabling users to quickly access job details and logs.

**Describe alternatives you've considered**
Manually searching for the CodeBuild job associated with each module deployment is an option, but it is time-consuming and disrupts the workflow.

**Comment by dgraeber** [comment]
@zaremb I believe we can always proved the Codebuild URL if in `debug` mode...but unfortunately only after the build has completed (in seedfarmer).   I can do some research on CodeSeeder regarding providing this data earlier, but preliminarily i know we can support the URL after successful job completion
