### ISSUE TITLE
[FEATURE] - Simple API to retrieve deployment specific metadata

### ISSUE THREAD

**Issue by otyrrell** [awslabs/seed-farmer#328]
Currently when running integration tests we need to know the deployment specific ARN's of the relevant resources. These are often stored as module metadata anyway so if we had a function with the same effect as below we could easily refer to resources consistently between deployments

`def _get_deployment_metadata(self):

        deployment_specific_parameter_path = (
            f"/{seedfarmer_definition['project']}/{os.getenv('GLOBAL_DEPLOYMENT_ID')}/"
        )
        logger.info(f"getting metadata for path: {deployment_specific_parameter_path}")
        ssm_client = self.ci_session.client("ssm")
        search_terms = {
            "Path": deployment_specific_parameter_path,
            "Recursive": True,
        }

        response = ssm_client.get_parameters_by_path(**search_terms)
        logger.info(response)
        ssm_params = response["Parameters"]
        while "NextToken" in response.keys():
            response = ssm_client.get_parameters_by_path(
                NextToken=response["NextToken"], **search_terms
            )
            logger.info(response)
            ssm_params += response["Parameters"]

        # Filter to only metadata parameters
        metadata_params = [
            param for param in ssm_params if param["Name"].endswith("metadata")
        ]

        # gice deployment agnostic reference to group/module
        formatted_params = {}
        for param in metadata_params:
            module_id = (
                param["Name"]
                .removeprefix(deployment_specific_parameter_path)
                .removesuffix("/metadata")
            )
            formatted_params[module_id] = json.loads(param["Value"])

        self.deployment_metadata = formatted_params`

**Comment by dgraeber** [comment]
Same as #326
