### ISSUE TITLE
[FEATURE] Simple API to retrieve metadata parameters in stack definition as they are defined in module manifests

### ISSUE THREAD

**Issue by otyrrell** [awslabs/seed-farmer#329]
Currently when data is passed into a module from a manifest, to retrieve that variable I need to know more information than just the key value that was assigned in the manifest. Therefore we end up writing boiler plate code to make the referencing of these variables clean within the stack definition. 

Could we have something equivalent as a method of the seedfarmer module?
`def remove_prefix(prefix, string):
    if string.startswith(prefix):
        return string[len(prefix) :]
    return string

def get_parameters() -> dict:
    prefix = f"{os.getenv('AWS_CODESEEDER_NAME').upper()}_PARAMETER_"
    params = {}
    for key, value in os.environ.items():
        if key.startswith(prefix):
            params[remove_prefix(prefix=prefix, string=key)] = value
    return params

service_name = os.getenv("AWS_CODESEEDER_NAME")
seed_prefix = service_name.upper().replace("-", "_") + "_"
deployment_name = os.getenv(f"{seed_prefix}DEPLOYMENT_NAME")
module_name = os.getenv(f"{seed_prefix}MODULE_NAME")
stack_name = f"{service_name}-{deployment_name}-{module_name}"`

**Comment by dgraeber** [comment]
@otyrrell We do have the ability to add a data-file that is outside of the module (and can be referenced by gitpath).

This will allow you to write your own boilerplate code and include it in every module without modifying the module code:

https://seed-farmer.readthedocs.io/en/latest/manifests.html#deployment-manifest

Please refer to dataFiles

**Comment by dgraeber** [comment]
Closing for now due to lack of response.  Can be reopened
