### ISSUE TITLE
[FEATURE] - Reduction in boilerplate code required for publishing CfnOutputs as metadata

### ISSUE THREAD

**Issue by otyrrell** [awslabs/seed-farmer#330]
Currently we need to repeat standard boiler plate code between modules which takes the CfnOutput and writes this as a json file.

If we had a CLI command from seedfarmer we would remove error prone code like this like this in the deployspec.yml

` - export ADDF_MODULE_METADATA=$(python -c "import json; file=open('cdk-exports.json'); print(json.load(file)['addf-${ADDF_DEPLOYMENT_NAME}-${ADDF_MODULE_NAME}']['metadata'])")`

and replace it with something like this

`seedfarmer metadataexport cdk-exports.json`

**Comment by dgraeber** [comment]
@otyrrell as each module / use case can be different, I don't think we can provide a generic method per-se.  But, we do have the ability to add a data-file that is outside of the module (and can be referenced by gitpath).

This will allow you to write your own boilerplate code and include it in every module without modifying the module code:

https://seed-farmer.readthedocs.io/en/latest/manifests.html#deployment-manifest

Please refer to `dataFiles`

**Comment by dgraeber** [comment]
Closing for now due to lack of response.  Can be reopened

**Comment by dgraeber** [comment]
@otyrrell we are reopening to re-evaluate....sorry for the delay

**Comment by dgraeber** [comment]
Exploring adding CLI support for the following scenarios:
- adding an output key/value to the metadata
- converting the cdk output json to metadata (based on passing in the nested json path of the anticipated output)

**Comment by dgraeber** [comment]
This has been added...once released, there will be docs at:

https://seed-farmer.readthedocs.io/en/latest/module_development.html#deployspec-cli-helper-commands
