### ISSUE TITLE
[FEATURE] Allow for defintion of a custom IAM policy as part of bootstrap process

### ISSUE THREAD

**Issue by AndyEfaa** [awslabs/seed-farmer#352]
Every seedfarmer deployment requires the underlying AWS Account to be seedfarmer-bootstraped via the command `seedfarmer bootstrap `. This bootstrap process defines IAM policies that govern seedfarmer's access permissions according to security best-practices.

In certain cases, an end user might need to customize the default IAM policy to adjust for their specific deployment scenarios. (Example: Access specific SSM params outside of the default scope.)

We suggest to allow for the customization of the generated IAM policy by passing in a custom IAM policy name into the seedfarmer bootstrap process. Possible implementations:
- `seedfarmer bootstrap target --synth --overwrite-default-role-policy MyCustomPolicyName`
OR
- `seedfarmer bootstrap target --synth --attach-additional-role-policy MyCustomPolicyName`

The documentation should mention how an end user can extract the current default policy, so that a valid starting point exists for creating a customized policy.

**Comment by dgraeber** [comment]
Thanks for this request.  Some background: the `seedfarmer-<project>-deployment-role` has the minimum required permissions to allow seedfarmer to function properly.  We are not opposed if end users enhance the permissions (attach additional policies) given our shared-responsibility model.  But the permissions provided MUST be left intact...you can add to them but not restrict them.  We can explore how to make it easier to attach a managed policy to the deployment role via the CLI (whether executing or applying a synth).

The CLI does have `--help` features to define how to use the parameters.  The `--synth` command is available to generate and print / write out a valid CFN template with the minimum default policy information.  Via this method, end users can capture and execute the CFN template (modified or as-is) in the proper accounts.  Of course, the shared-responsibility model is in full-effect here.

REF: https://seed-farmer.readthedocs.io/en/latest/bootstrapping.html

**Comment by dgraeber** [comment]
@AndyEfaa After reviewing this, I may need to to require the ARN (s) to be passed in instead of the names.  This could  propose a wrinkle as IF this is a customer-managed-policy, the account id NEEDS to be correct.
Lets chat?

**Comment by chamcca** [comment]
do you have  a specific use case that requires modification of the target role policy? the operations performed by the target role are very specific to the seedfarmer CLI. adding additional permissions should not be necessary so would be interested to hear if this is not the case.

**Comment by AndyEfaa** [comment]
> do you have a specific use case that requires modification of the target role policy? the operations performed by the target role are very specific to the seedfarmer CLI. adding additional permissions should not be necessary so would be interested to hear if this is not the case.

To provide a very specific example: 
In our current project, we want to reference various pre-populated SSM parameters for VPC Id (with a path outside of the current deployment) in the deployment.yaml. As of today, this is not possible due to the policy restrictions.
