### ISSUE TITLE
[BUG] modules referenced by codecommit git link fail to clone

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#376]
**Describe the bug**
Modules referenced by git link using codecommit fail to clone in seedfarmer 2.9.3:
```
[...]/python3.9/site-packages/git/cmd.py",line477,in check_unsafe_protocols
raise UnsafeProtocolerror git.exc.UnsafeProtocolError: The "codecommit:
protocol looks suspicious, use allow_unsafe_protocols-True' to allow it.
```

**To Reproduce**
0. Use version 2.9.3 of seedfarmer
1. Set any of the module path to start with:
`git::codecommit::`
2. Try to run seedfarmer deployment

**Comment by dgraeber** [comment]
Please provide a sample mamifest as there are now multiple scenarios wre support (tags, commitbhashes, branches, and off main)

**Comment by zaremb** [comment]
Ive tried both hash and tag, same error

**Comment by dgraeber** [comment]
issue replicated....remediation identified and PR coming
