### ISSUE TITLE
[BUG] changes in env variables that are inputs to seedfarmer does not cause redeploy

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#386]
**Describe the Bug**
Given the module that has a input from env variable, change in env variable does not cause redeploy of that module

**To Reproduce**
0. Have a module that accepts env var as an input
1. Deploy the module
2. Change the env var value, do not change anything in the module
3. Run dry run. Module will be marked as up to date

**Expected behavior**
Module is redeployed because input variable has changed

**Comment by dgraeber** [comment]
This is as-designed.  We are not tracking the .env variables as part of the module changeset (checksum evaluation) as it are not tied to any particular module.

**Comment by dgraeber** [comment]
I will leave this open for feedback.
