### ISSUE TITLE
[FEATURE] Redeploy the module when input env vars for the module have changed

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#387]
**Is your feature request related to a problem? Please describe.**
Currently changes to environment variables/.env files are not tracked and seedfarmer does not redeploy the module. I am using the same deployment manifest between dev and prod environments

I am using .env files to pass information between environments. . You can think of it as the bucket names that i already have in my dev and prod account. Sometimes, I need to change those bucket names. If i change the names in dev.env, seedfarmer will not recognize this change. I have to go to ssm or use cli to remove module metadata, and run seedfarmer again. 

**Describe the solution you'd like**
Seedfarmer would recognize the changes in input variables

**Describe alternatives you've considered**
Removing ssm params manually

**Additional context**
It would also be nice to have a cli command to force seedfarmer to update specific module. It would not fix the problem, but i would not have to remove the ssm param values manually and trigger entire deployment

**Comment by dgraeber** [comment]
After reviewing this, we determined that supporting this feature would have unintended side effects that would be detrimental to functionality.
