### ISSUE TITLE
[FEATURE] seedfarmer apply works out of box in China regions

### ISSUE THREAD

**Issue by danxie1999** [awslabs/seed-farmer#388]
**Is your feature request related to a problem? Please describe.**
The seedfarmer apply cannot run directly in China regions.
error message when run:

  File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws-cn:iam::641482327773:user/ingest-test is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::641482327773:role/seedfarmer-addf-toolchain-role

**Describe the solution you'd like**
Need to update the partition from arn:aws to arn:aws-cn in the seed-farmer python lib.

**Comment by dgraeber** [comment]
@danxie1999 Thanks for your feature request.  We will review and assess
