### ISSUE TITLE
Seedfarmer not validating required envVariable

### ISSUE THREAD

**Issue by freuthli-qc** [awslabs/seed-farmer#392]
**Describe the bug**
I am not totally sure if a bug or not, but I would guess it being a bug.
Problem is: in our project we defined parameters taken from envVariable, for most seedfarmer would also successfully validate if they were set in the env, but for one it does not (and I cannot understand why):

```
  - name: stage
    valueFrom:
      envVariable: STAGE
```

I can run seedfarmer apply, while `env | grep "STAGE"` yields nothing

**To Reproduce**
1. create a manifest that uses multiple variables taken from envVariable, also one that is called referring to env variable STAGE
2. use this varible somewhere in the code
3. run seedfarmer apply
4. See seedfarmer running (without failing on validating that this envVariable is missing), code will run with "STAGE"=""

**Expected behavior**
Any envVariable is validated, also if you call an variable as mentioned above, script would not start but raise an error before running any apply

**Comment by dgraeber** [comment]
Hi @freuthli-qc  - thanks for this issue request.  If i am understanding your issue...Yes, currently when referencing an env variable in the `Parameters` section of a module definition, we are not doing any validation as to whether the variable is available.

In order to stop processing, we would need to raise an error when the parameter is referenced for that module....as opposed to validating ALL env parameters at initial request.

Please comment?

**Comment by freuthli-qc** [comment]
It is defined in module manifest.
If you are not doing any validation, how come that if some other env variable is missing SF will fail before starting to run anything?

**Comment by freuthli-qc** [comment]
@zaremb should be aware about our project setup, where this is coming from

**Comment by dgraeber** [comment]
@freuthli-qc @zaremb
Thanks for this input, I now understand what you are doing.  Currently, the env parameter support is for module parameters, and for account id resolution.  We do not currently support resolution of env variables for the `name` field in deployment manifests and in module manifests.  REF: (https://seed-farmer.readthedocs.io/en/latest/manifests.html#environment-variables).


Perhaps this should be requested as a `Feature`

**Comment by freuthli-qc** [comment]
Ok, thanks for clarifying this.
It would in deed be great if SeedFarmer could validate if required envVariables are set in the env and in case they are not could fail in the beginning rather then creating a maybe screwed up deployment, since using an envVariable without providing it would just create incorrect deployment as far as I am concerned.

**Comment by dgraeber** [comment]
We can definitely raise errors if the envVariable that a `Parameter` references is not available (when used in the account id, the deployment currently does raise an error) when the modules go to deploy.
