### ISSUE TITLE
[FEATURE] --dry-run supports running some pre-build or test commands in each module

### ISSUE THREAD

**Issue by kevinsoucy** [awslabs/seed-farmer#408]
**Is your feature request related to a problem? Please describe.**
Our customers have asked us for a faster/better way to test locally that module updates are error-free and deployable. Currently there is no easy way within a module (whether its a terraform or cdk application) to compile the stacks and test that there are no syntax errors for example. When running the --dry-run, no commands from the deployspec are run. 

**Describe the solution you'd like**
One possible solution would be to execute the commands in each module's deployspec under the deploy section but prior to the build phase (eg install and pre_build):

deploy:
--
2 | phases:
3 | install:
4 | commands:
5 | - npm install -g aws-cdk@2.20.0
6 | - pip install -r requirements.txt

**Describe alternatives you've considered**
Or we add a completely new section to the deployspec.yaml which could be like:

test:
3 | install:
4 | commands:
5 | - npm install -g aws-cdk@2.20.0
6 | - pip install -r requirements.txt

which gets executed in CodeBuild to test that the stacks compile. I understand this gets quite complicated with parameters being passed between modules. 

Another option is to use the local CodeBuild Agent to run locally: https://docs.aws.amazon.com/codebuild/latest/userguide/use-codebuild-agent.html

**Additional context**

**Comment by dgraeber** [comment]
As previously discussed, due to the nature of SF this is not possible.  The addition of the support to fetch and export env parameters is available so that the content of the deployspec can be run (ex cdk apply) but that is the extent we can externalize.  We are looking at how to improve local development experience at the moment.
