### ISSUE TITLE
SeedFarmer NameGenerator not supporting delimiter or infix - also not documented

### ISSUE THREAD

**Issue by freuthli-qc** [awslabs/seed-farmer#409]
1. In our project people are using NameGenerator in a way that I found is actually not really supported in code and I don't know, where this implicit expectation would come from. Here an example how someone used it:

```yaml
nameGenerator:
  prefix: "myprefix"
  value: "-"
  suffix: "mysuffix"
```

I do see that NameGenerator will concatenate the prefix and suffix without any delimiter. But being able to define a delimiter would be a great thing -> https://github.com/awslabs/seed-farmer/blob/9ed1c3af20ee37c2b14791df810a80fb1e4d2e0b/seedfarmer/models/manifests/_deployment_manifest.py#L145

I guess their expectation would be that NameGenerator does: "${prefix}${value}${suffix}". In this case the value could also be a infix.

2. What also would be nice to be able to provide an "infix" parameter that is used in the middle.

=> If we would combine both ideas, concatenating the name might be a bit more difficult, but being able to provide:
1. prefix
2. infix
3. suffix
4. delimiter

would really help to avoid that users will again do their own way of string concatenation.

**Comment by forszpanen** [comment]
Yes - please add it to Doc. Common use case is when we have feature branches and we want to deploy sth after dry-run.

**Comment by dgraeber** [comment]
It will be added it to the docs.

@freuthli-qc after deliberating, we decided that we will leave the feature as designed in order to maintain consistency with existing users (but document it properly).

**Comment by dgraeber** [comment]
Will be in the docs on the next patch or minor release
