### ISSUE TITLE
[FEATURE] Update codeseeder CodeBuild project when upgrading seed farmer

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#416]
**Is your feature request related to a problem? Please describe.**
My codeseeder codebuild project was failing due to issues with codebuild image. I created it with old version of seedfarmer and I think that was the reason. I have installed new seedfarmer version and ran seedfarmer apply and error was still present. Then I deleted codeseeder CloudFormation stack and ran seedfarmer apply, codeseeder project was recreated, and the issue was fixed. Based on this, I think seedfarmer codebuild project is not getting updated when seedfarmer version is updated.

**Describe the solution you'd like**
Codeseeder cloudformation stack gets updated when seedfarmer version gets updated (and seedfarmer apply command is run)

**Comment by dgraeber** [comment]
That is correct: seed-farmer only checks if an AWS CodeSeeder seedkit has been deployed - it does not check anything about the version of the seedkit as that is outside the functionality of the seed-farmer cli.  

Automatically updating a seedkit from seedfarmer will have unintentional side effects.   The proper way to manage the code build project is to use the codeseeder cli to manage the seedkit.  We added the checks in seed-farmer as a convenience method to make sure all dependencies are met, but we are not managing those dependencies.

**Comment by zaremb** [comment]
I disagree that is the proper way for the user of seedfarmer. As a user of seedfarmer, I am only using codeseeder indirectly. It is very surprising that I need to update a resource managed by a tool that is part of seedfarmer to upgrade seedfarmer. 

In any case, I would like to ask for documentation on how to upgrade seedfarmer, such that codebuild project is also upgraded.

**Comment by dgraeber** [comment]
AWS-CodeSeeder and SeedFarmer are separate tools.  This is not managed by seedfarmer.    I am sorry you disagree and we will work to make the tooling amenable to everyone, but your request cannot be supported at this time.

In order to upgrade the seedkit, you need to destroy it and let seedfarmer redeploy it via the CodeSeeder API.  In the target account/region - look for the seedkit stack `aws-codeseeder-<project>` and delete it.

**Comment by dgraeber** [comment]
After talking with @zaremb - we will add more detailed info to the seed-farmer documentation telling users how to delete and regenerate the AWS CodeSeeder seedkit ...
