### ISSUE TITLE
[BUG] Modulestack not respected when module refered with git path

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#417]
**Describe the bug**
Modulestack of module referenced by git path is ignored. I.e.
```name: foo
path: git::codecommit::REGION://ACCOUNT@repo.git//modules/foo/?ref=abc
parameters:
[...]

```
Does not have policy from modulestack.yaml deployed at all.
However, same module with path
```
path: /Users/foo/PROJECT-NAME/modules/foo
```
has policy from module stack deployed.

**Comment by dgraeber** [comment]
Is this occurring on other modules that are also sourced via git and are also using a modulestack.yaml?
Can you elaborate on the details?  Was this module successfully deploying previously in other deployments?  Did it successfully deploy in this deployment or not at all in this deployment?  

Please reach me via email / slack.

**Comment by zaremb** [comment]
Closing as I could not replicate it anymore
