### ISSUE TITLE
[FEATURE] Allow exporting moduledata outputs directly to environment or .env file

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#42]
**Is your feature request related to a problem? Please describe.**
When developing new modules, your module might have many dependencies on other modules. To allow local development for instance of CDK applications, you need the resolved values from other module outputs to be available as environment variables for your in progress module locally. 

You can already get the module specific output you need, e.g.:
`seedfarmer list moduledata -d <deployment_name> -g <group_name> -m <module_name>`

**Describe the solution you'd like**
I would like to be able to export the moduledata 
`seedfarmer list moduledata -d <deployment_name> -g <group_name> -m <module_name> --exportable`

Outputs:
unix
```
export MODULE_OUTPUT_1=foo
export MODULE_OUPUT_2=bar
```

windows (optional)
```
set MODULE_OUTPUT_1=foo
set MODULE_OUTPUT_2=bar
```

This should allow me to redirect the export output to an .env file with ` > .env` and then source the file to expose the variables as environment variables in the terminal

**Describe alternatives you've considered**
Manually building scrip to do parsing from output format to format above

**Comment by dgraeber** [comment]
This can be done.  NOTE: this will only export the metadata stored, and prepend the project and parameter prefixes as if it were in a codebuild environment.
