### ISSUE TITLE
[BUG] Global parameter not available to be used by modules

### ISSUE THREAD

**Issue by gonzalobarbeito** [awslabs/seed-farmer#435]
**Describe the bug**
When loading a global parameter in a module's manifest, the global parameter is not available to the module

**To Reproduce**
1. Add a Global Parameter in deployment.yaml (e.g. xx)
2. reference that parameter in a module manifest using valueFrom: parameterValue: xx
3. try to deploy
4. See error: seedfarmer.errors.seedfarmer_errors.InvalidManifestError: The parameter value defined (xx) is not available

**Expected behavior**
The parameter should be properly imported to the module being deployed

**Comment by dgraeber** [comment]
will be in next release
