### ISSUE TITLE
[FEATURE] Creation of change sets until ChangeSet limit is hit

### ISSUE THREAD

**Issue by gonzalobarbeito** [awslabs/seed-farmer#441]
**Describe the bug**
Seedfarmer creates a Cloudformation change set at the beginning of a deployment, failed change sets are not automatically deleted and when the limit is hit, no deployment can be started. Upon inspection of failed change sets registered, all of these contained no changes.

**To Reproduce**

1. deployment.yaml contains several groups, each group including several modules
2. Deployment command: `seedfarmer apply manifests/deployment.yaml --debug --env-file config/$NAMESPACE.env`
3. Deployments work correctly until reaching Cloudformation changeset limit (1000?)
4. When limit is reached, `seedfarmer apply` fails with following error:
`botocore.errorfactory.LimitExceededException: An error occurred (LimitExceededException) when calling the CreateChangeSet operation: ChangeSet limit exceeded for stack arn:aws:cloudformation:REGION:ACCOUNT:stack/aws-codeseeder-addf/ID`

**Expected behavior**
Not recording empty changes in change set to avoid hitting CloudFormation limit.

**Context**

1. **workaround solution**: Deletion of failed CloudFormation change sets, an example script can be found [here](https://rod.tech.blog/2021/03/15/fixing-an-error-occurred-limitexceededexception-when-calling-the-createchangeset-operation/).
2. **Where to find CloudFormation change sets**: 
2.1. Access the AWS console 
2.2 Go to CloudFormation -> Stacks -> In search bar: `aws-codeseeder-addf `
2.3: In the menu bar, select Change sets, you should be able to see several failed change sets created by AWS CodeSeeder CLI
3. This behaviour can also be seen in this [issue](https://github.com/aws/aws-cli/issues/4534).

**Comment by dgraeber** [comment]
A couple of thoughts:
1. I have no idea what is being updated here (you did not denote if a module or whatever)...so to reproduce is not possible
2. SeedFarmer checks CFN template deployments but not changesets, the modules apply CDK changes
3. I fail to see how seedfarmer can delete changesest if limits are hit

This sounds more like an issue with the limits on the AWS account...???

**Comment by dgraeber** [comment]
Changed this to a feature.  

Reviewing the history and online git issues, this sounds like an issue with the CFN and you are looking to cover the problem with a band-aid.  We are evaluating whether we should be doing this in seedfarmer

**Comment by dgraeber** [comment]
This is not something we should incorporate into seed-farmer
