### ISSUE TITLE
[BUG] No redeployment after updating global parameter

### ISSUE THREAD

**Issue by gonzalobarbeito** [awslabs/seed-farmer#451]
**Describe the bug**
After a successful deployment using Seedfarmer that uses a reference to a global parameter (i.e. `parametersGlobal`) in one or more modules, if we change the referenced value in the `deployment.yaml` file, Seedfarmer won't pick up that change and redeploy affected modules.

**To Reproduce**
1. Create a global parameter in deployment.yaml, and reference it in one or more modules:

In `deployment.yaml`:
```
targetAccountMappings:
[...]
    parametersGlobal:
      foo: bar
[...]
```
In `example-module.yaml`:
```
- name: ecr-repo-tag
    valueFrom:
      parameterValue: foo
```
3. Deploy using Seedfarmer: 

`seedfarmer apply manifests/realm-infra/deployment.yaml --debug`

8. Change that global parameter to any other value:
```
targetAccountMappings:
[...]
    parametersGlobal:
      foo: baz
[...]
```
9. All modules deployed will be up to date (no module redeployment with new global parameter value)

**Expected behavior**
Seedfarmer redeploys modules that reference that updated global parameter

**Comment by dgraeber** [comment]
@gonzalobarbeito Yes, this is as-designed.  Seed-Farrmer and modules are module-centric, in that everything revolves around the module, it's code and metadata.  The global parameters are defined in the deployment.yaml manifest and apply to all modules, but are only metadata that is not taken into the changeset criteria.  This was designed in this fashion b/c a signal to apply changes on a change to the deployment manifest would trigger a redeployment of all modules in the deployment...which is opposite the design methodology.

Leaving this issue open for now....lets debate offline.
