### ISSUE TITLE
[FEATURE] Add flag to enable Lambda for CodeBuild module Deployment jobs

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#456]
AWS released option to choose Lambda as compute for CodeBuild:
https://aws.amazon.com/about-aws/whats-new/2023/11/aws-codebuild-lambda-compute/

Some of the modules I have would be a good fit (they deploy simple CDK apps that would not hit 15 mins runtime limit). It would be great to explore option on specifying Lambda compute for module deployment jobs. I would imagine it as a flag in module manifest.

**Comment by dgraeber** [comment]
This is an interesting suggestion and one that we can evaluate (once we get some time).  

Can you elaborate on the perceived benefit?  Why would this be advantageous to your use case?

**Comment by zaremb** [comment]
Sure. Reducing provisioning time will be big benefit. Most of my module deployments take 1-3 mins. I have about 13 groups of modules, so potentially we look at around 3-6 mins provisioning time (~30 seconds per module deployment job) which could be saved.

**Comment by dgraeber** [comment]
We have evaluated this request.  @zaremb ping me and we can discuss reasons...
Closing this issue.
