### ISSUE TITLE
[FEATURE] Support setting version specifier in seedfarmer.yaml

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#463]
**Is your feature request related to a problem? Please describe.**
When new seedfarmer releases include critical features or updates that is important, we try to update the project to use the latest seedfarmer version. However, since we work in large, distributed teams, some members might inadvertently be using an older version of seedfarmer

**Describe the solution you'd like**
Add support for a property in the seedfarmer.yaml that allows setting a version using the python version specifier specification (https://peps.python.org/pep-0440/#version-specifiers). 

When seedfarmer commands are run, compare current seedfarmer version against the version in the seedfarmer.yaml, and if there is a mismatch, throw an error requesting the user to upgrade to a supported seedfarmer version.

**Describe alternatives you've considered**
Add wrapper scripts around seedfarmer to evaluate requirements.txt | grep seedfarmer to compare versions

**Additional context**
Allows us to capture versioning requirements for seedfarmer as code.

**Comment by dgraeber** [comment]
Will be in next release
