### ISSUE TITLE
[BUG] Failed deployment due to missing parameters(deprovision storage gateways)

### ISSUE THREAD

**Issue by mehdikmotlagh** [awslabs/seed-farmer#465]
We are using seed-farmer v2.10.5 for an ADDF application in AWS. 
In our manifest file Deployment.yaml we define several groups of modules to deploy, such as "storage-gateway" and "gateway-activation".
However, now we want to deprovision these two groups, "storage-gateway" and "gateway-activation". 
To do so, we just commented out those groups in the Deployment.yaml to force Seedfarmer to destroy the deployed resources.
When running "seedfarmer apply" we fail with this error:

Command did not exit successfully seedfarmer apply manifests/realm-infra/Deployment.yaml --debug --env-file config/$BRANCH.env exit status 1
 
seedfarmer.errors.seedfarmer_errors.InvalidManifestError: The module metadata parameter (name='storage-gateway' group='gateway' key='storageGatewayInstanceId') is not available
 
DEBUG | _parameter_commands.py: 59 | ThreadPoolExecutor-2_0 ] parameter: {'value_from': {'module_metadata': {'name': 'storage-gateway', 'group': 'gateway', 'key': 'storageGatewayInstanceId'}, 'env_variable': None, 'parameter_store': None, 'secrets_manager': None, 'parameter_value': None}, 'name': 'sgw-instance-id', 'value': None, 'version': None}
 
DEBUG | _parameter_commands.py:147 | ThreadPoolExecutor-2_0 ] Loading metadata for dependency group, module: gateway, storage-gateway
DEBUG | _parameter_commands.py:153 | ThreadPoolExecutor-2_0 ] loaded parameter value: {}
DEBUG | _parameter_commands.py:160 | ThreadPoolExecutor-2_0 ] parsed parameter value: None
 
 
It seems that Seedfamer is looking for parameters that do not exist to destroy the resources. We have also tried manually deleting all the Cloudformation Stacks related to these two module groups, but we get the same error.
 
The question is, how can we solve this issue? Is there a way to force seedfarmer to ignore the destruction of these modules, since we have already taken the liberty of manually removing the stacks themselves from AWS Console?

**Comment by dgraeber** [comment]
@mehdikmotlagh It sounds like the export (writing) of the module metadata of `gateway-storage-gateway` did not occur (a bug in the module?) when it was deployed?  You can always check the metadata via `seedfarmer list moduledata -d <> -g<> -m<>`

To unstick your deployment, first define the what the project, deployment , group and module names are....you can delete ONLY the ssm parameters associated with that module...

In the target account and region, go to SSM, and filter on:
`/<project>/<deployment>/<group>/<module>' and delete those parameters....seedfarmer will then ignore all artifacts associated with them

ex:
project = addf
deployment = aws-solutions
group = analysis
module = testing

Filter in SSM on:
`/addf/aws-solutions/analysis/testing` and delete those entries
