### ISSUE TITLE
[FEATURE] Hint if user may be using wrong account

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#471]
**Is your feature request related to a problem? Please describe.**
Quite often I find myself or colleagues exporting wrong credentials when running seedfarmer apply. As a typical user, you get not so obvious message then, i.e: 
```
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::[...] is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::[...]

```
It would be great to hint the user that they may be using wrong account or region.
**Describe the solution you'd like**
Store in some cache file i.e. `.seedfarmer-cache` hash (or plain text, to be evaluated from security perspective) of previously used account id and region. Then, one could catch AccessDenied when assuming role and print error with nice error message like: `It seems you have used different account (012345678910) previously. Please confirm you have right credentials for correct account`

**Comment by dgraeber** [comment]
Adding comments for what to check (is the account set in the manifest, did you specify the correct region, etc) are all valid requests and we can definitely help here.

I need to evaluate the caching of account id's on the local invocation for feedback....(i.e. if there are security implications as we won't store it in clear text on a local filesystem)

**Comment by zaremb** [comment]
Hello, is there any update on this Feature Request?

**Comment by dgraeber** [comment]
Yes...it is in process

**Comment by dgraeber** [comment]
Info related to assuming the toolchain session and the deployment sessions have been added with hints.  As the roles are global, we cannot indicate whether the region is correct / incorrect but did add hints to look at the account id in the ARN's for verification.
