### ISSUE TITLE
[FEATURE] Add an auto-destroy feature destroying artifacts.

### ISSUE THREAD

**Issue by Yaccoub** [awslabs/seed-farmer#479]
**Is your feature request related to a problem? Please describe.**
Quite often I find myself or colleagues forgetting to destroy all the modules related to a given deployment after some test deployments.

**Describe the solution you'd like**
Is there a possibility to have a kind of auto-destroy feature for the current deployment to destroy all the artifacts from said deployment triggered after a fixed period of time. Once this time span is expired all artifacts can be destroyed. 

**Additional context**
Aim of this feature is to create some sort of automatism for deleting artifacts created by deployments.

**Comment by malachi-constant** [comment]
I'd be a bit worried about adding a feature that can destroy resources without explicit targeting by seed-farmer. But i'll let the rest of the team weigh in here as well.

Have you considered tools like CloudCustodian, or potentially setting up an EventRule to trigger a CodeBuild job that runs seedfarmer destroy at a defined interval?

**Comment by dgraeber** [comment]
@Yaccoub Thanks for this input.  Unfortunately, this is not something we would include in SeedFarmer as the intent is to be event-driven via gitops.  Perhaps you could create a micro ec2-instance with a cron, or a codepipeline job that is initiated by a CW event.   But embedding this logic into SeedFarmer over-extends its function.  The logic of when to deploy or destroy must exist outside this library.
