### ISSUE TITLE
[Feature Request] Enable termination/retirement of modules

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#5]
The current workflow for destroying already deployed modules results in an error when there was an issue in the deployspec destroy segment. 

When a module/group is simply commented out from the deployment.yaml file, the diff calculation figures out the modules to destroy, but since there is no access to the most up to date deployspec (as it isn't bundled, the deployspec is read from SSM), changes to the destroy code does not get updated before attempting to destroy.

Refine the workflow for removing already deployed modules/groups. Add support for a mechanism to cleanly terminate/retire/disable modules or groups that would still allow changes to the code and deployspec to be propagated.

**Comment by dgraeber** [comment]
Thanks for the request.  Though the root cause of the issue seems to be that the `destroy` part of the deployspec was faulty, we can look at adding CLI capability to update the deployspec of a deployed module to alleviate this issue.

**Comment by dgraeber** [comment]
In release/0.1.1
