### ISSUE TITLE
[FEATURE] Wildcards for 'filePath' in 'dataFiles' entry of manifests

### ISSUE THREAD

**Issue by m1cha3I** [awslabs/seed-farmer#522]
**Is your feature request related to a problem? Please describe.**
Currently, each file has to be specified separately for the dataFiles attribute. We are using those to facilitate a shared lib for seedfarmer modules. To not have to specify each additional file would ease use and maintenance for this use case.

**Describe the solution you'd like**
Instead of:
dataFiles:
  - filePath: libs/shared/a.py
  - filePath: libs/shared/infrastructure/b.py
 
wildcards analogues to the glob syntax would be helpful, i.e.,
dataFiles:
  - filePath: libs/**/*.py

**Describe alternatives you've considered**
Alternative, a 'directoryPath' solution would also suffice

**Additional context**
It is important that relative path structures are conserved the same way as is already for the dedicated specification of files.

**Comment by dgraeber** [comment]
@m1cha3I Thanks for this request.  To give some background: the dataFiles are apart of the calculation to determine if a module has changed, so each file needs to be defined.  The relative path structures are always intact in dataFile support, but the support for a wildcard path or a directoryPath introduces possible conflicts in the manner in which change detection is implemented.   I will review this with the team and explore possibilities.

If you are intending to include python scripts for execution, perhaps using the seedkit support for AWS CodeArtifact.  You can install your own custom python library in CodeArtifact and pip install from your deployspec as needed.  This would need to be done in every target account / region mapping in which a module would need to reference it:
`codeseeder deploy seedkit <project-name> --deploy-codeartifact`

**Comment by m1cha3I** [comment]
@dgraeber Thank you for your feedback/information and taking into consideration, much appreciated.

**Comment by dgraeber** [comment]
@m1cha3I sorry for the delay ( I had thought i did reply with the findings).

The inclusion of a wildcard may have unintended side effects that we could not mitigate.  For example, if referring to a wildcard path to be inclusive for a majority of modules - if one file has changed that may trigger a redeployment of all modules that refer to the wild-carded path...even if the file that has changed is not used in the manifest.

We will look for other options to help support this, but I am closing this FR for now.

**Comment by m1cha3I** [comment]
@dgraeber No worries, thank you for the feedback and consideration
