### ISSUE TITLE
[FEATURE] Improved documentation on CLI commands and Options

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#525]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to have detailed documentation of all CLI commands available, their defaults and what they do with detail.
https://seed-farmer.readthedocs.io/en/stable/cli_commands.html

This becomes especially important with the introduction of new flags/options and should provide more context than the command line help output might. 

Could potentially be auto-generated detailed documentation from code comments:
e.g https://pypi.org/project/mkdocs-click/

**Describe alternatives you've considered**
Commands/Options can be discovered using `seedfarmer <command> --help`. But the description for these are sometimes limited. Discovery of the appropriate commands would be simpler when they are part of the documentation

**Additional context**
Some information that needed to be looked up using `$ seedfarmer --help`:
- What  `--enable-session-timeout / --disable-session-timeout` does
- What `--update-seedkit` would do (as a customer, I do not know this)
- What `$ seedfarmer store` commands do or are useful for (nothing in the docs)
- What `$ seedfarmer remove moduledata`does
- When to use `$ seedfarmer list buildparams`
- What to do to export module metadata as `.env` files for local development (using `--export-local-env` for instance)

**Comment by dgraeber** [comment]
We are currently using sphinx...so I will research https://sphinx-click.readthedocs.io/en/latest/

NOTE: i did not know whether using Mkdocs or Sphinx was such a heated topic.  I am also thinking of converting
