### ISSUE TITLE
[FEATURE] Store commit hash for which a module code has been deployed

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#529]
**Is your feature request related to a problem? Please describe.**
Currently, when a module needs to be destroyed, the local module code needs to be in sync with the stored manifest in SSM. 

Whenever for instance the module code has changed to include a new parameter, destruction is no longer possible as the code would fail to synthesize as it fails when trying to read the parameter via `os.environ["KEY"]`.

**Describe the solution you'd like**
In order to allow users to sync their local module code with what has been deployed and the manifest stored, allow them to figure out which commit hash was used to deploy each module.

This commit hash should be stored together with the module metadata (also in SSM) and should be easily retrievable via a seedfarmer command. 

**Describe alternatives you've considered**
A complete re-engineering of the destruction logic that also stores copies of the code used to deploy the module, enforcing synchronization between stored manifest and module code.

Note: This would require mechanisms to update both the deployspec (`seedfarmer store deployspec ...`) and potentially a mechanism to update the stored manifest (in case of error).

**Comment by kevinsoucy** [comment]
My team faces an issue like this on a weekly basis.

**Comment by dgraeber** [comment]
I want to make sure I understand the ask: if you deploy via referencing a gitpath, you want SF to persist the resolved commit hash and tie to the deployment.   This is to support a CLI that will tell the user what the has is so they can pull that exact code?  And provide a CLI (`seedfarmer list githash -d <d> -g<g> -m<m>` )

Once you get the hash, what will you do with it on destroy?  The manifest used to destroy is already in SSM, and since you are using a gitpath, it is not like you can fetch the code locally and use that.  The only way is to change the stored SSM parameter (similar to deployspec)....but that sounds like a bad thing to do.

How will the commit hash be used to destroy an existing module? 

We are reviewing storing the module code if local code is used, but this problems sounds like it can be prevented by using proper git versioning schemes?  

Lets talk in detail.

**Comment by a13zen** [comment]
To be completely honest, this is to get past the issue of the manifest/deployspec used for destruction and the code used to do the destroying are constantly out of sync. 

Modules are only referenced via git-links for remote modules, most teams use local path references for modules they control. It makes sense because otherwise they would always need to push and update pointers while developing. 

So here is an exact scenario:

1. I am deploying Module A that takes as input the following parameter BUCKET_NAME.
2. As a developer I realize it should be a list of buckets and I change my CDK code to expect BUCKET_NAMES as parameter
3. I realize that I would need to destroy Module A, because it can't be updated. So I comment out the module in my manifest
4. I run seedfarmer apply, which takes the module deployspec/manifest from SSM, and CDK code from my local machine. Remember, this CDK code expects BUCKET_NAMES!
5. Seedfarmer runs the deployspec->destroy part of the stored manifest, but CDK can't synthesize for destruction because it is missing a REQUIRED parameter BUCKET_NAMES

At this point I'm in trouble. The manifest/deployspec & the CDK code have diverged. I need to destroy my old module A, but I can't with the code I have. To solve this I can:

Option A
1. Checkout an older version of the CDK code, that is exactly compatible with the manifest/deployspec
2. Comment the module and run seedfarmer apply

OR

Option B
1. I can modify the deployspec to provide a dummy value for the missing parameter (e.g. export BUCKET_NAMES=dummy)
2. Run seedfarmer store deployspec ... to update the stored deployspec
3. Run seedfarmer apply

OR

Option C
1. I can modify my local CDK code to provide a dummy value for destruction e.g. change os.eviron["BUCKET_NAMES"] to os.environ.get("BUCKET_NAMES"). This is not a great fix however because a/ it changes my deployment behaviour, b/ it will break for any resources that require specific formats e.g. ARNs.
2. Run seedfarmer apply

OR 

Option D (sadly most common solution right now)
1. I delete the stacks in cloudformation directly, hopefully deleting everything
2. I delete all metadata for the module from SSM to make seedfarmer forget it exists (very very error prone)


This feature request specifically aims to enable us to stop doing Option D and start doing Option A. 

The most ideal solution would be when the end user, doesn't care and the code/manifest/deployspec are always in sync

**Comment by dgraeber** [comment]
@a13zen Re-reading this - I can agree that none of the options are optimal.   I would go with Option A.  I have added support to record the git hash to 1\the module manifest 2\ the module metadata on successful deploy.  The githash can be fetched via the normal routes (`seedfarmer list moduledata`) if the module is sourced from a git-compliant repo.

That will provide a path forward with Option 1.  We can then discuss what an ideal solution should look like.
