### ISSUE TITLE
[FEATURE] Support global custom envVariable in Manifest file

### ISSUE THREAD

**Issue by danxie1999** [awslabs/seed-farmer#538]
**Is your feature request related to a problem? Please describe.**
In the manifest files, we do not want to always add fixed values instead for some values, we could would like to get them from environment variables. 
We noticed that some sections of the manifest files already support valueFrom -> envVariable (https://seed-farmer.readthedocs.io/en/latest/manifests.html).
  suffix:
    valueFrom:
        envVariable: SUFFIX_ENV_VARIABLE

Could you please make it work in all sections of manifest files?

**Describe the solution you'd like**
Make following syntax works for all secrions:
  <CustomValue>:
    valueFrom:
        envVariable: <ENV_NAME>

**Additional context**
If global custom environment variables can work in seedfarmer configuration files, it could really help us for code migration (ex. AWS EU to AWS China).

**Comment by dgraeber** [comment]
Hi @danxie1999 - Thanks for your request.  Our design tenets for SF focus on declarative manifests.  We added envVariable support for the following:
- module parameters
- global regional network definitions
- account id (to remove the need to commit to a repo the account id and provide extensibility)
- name generator for the Deployment name (to promote extensibility at large scale deployments)

Global and Regional Parameters themselves are just a set of dict strings and do not support the SF Parameter definitions, thus you cannot refer to SSM or SecretsManager or envVariables like the regional network sections.

This is the extent to which we decided to support envVariables as any further support will move away from declarative manifests to dynamic manifests...which introduces a significant amount of overhead for end users if used. 
 
We have consciously decided to limit the envVariable support to the areas that I denoted above, so we will not make the envVariable support available in all sections.

We can evaluate adding envVariable support for Global Parameters and regional parameters and weigh the benefits vs. risks that it will introduce.

**Comment by dgraeber** [comment]
I have reviewed the global and regional parameters.  They are implemented as freeform name/values (unlike the module parameters) and are not names (like network support and account id).  This follows with our decision to make them simple string dicts.  We will not be able to support envVariables for these values without a redesign of the way global and regional parameters are implemented - causing backward compatibility issues.
