### ISSUE TITLE
[BUG] TinyURLs truncated & Rate Limited

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#54]
**Describe the bug**
When running a deploy, seed-farmer outputs the link to codebuild logs as tinyurl link in a table. Clicking or copying the link from the built in VSCode terminal fails as it is truncated.

**To Reproduce**
1. Set terminal width to 80 characters or less
2. Run a deploy that fails from VSCode built in terminal.
3. Check the box for the "These modules had errors deploying"
4. Click & follow the link in the box directly from the terminal / Or copy the url

**Possible fix**

**Expected behavior**
Output full un-truncated CodeBuild URL directly in the console instead of table and not using tinyurl. A

**Screenshots**

<img width="514" alt="image" src="https://user-images.githubusercontent.com/85226895/181203551-4c3eedde-5d92-44e4-ba72-f0acf3875222.png">

This  opens up the browser for the truncated URL

<img width="576" alt="image" src="https://user-images.githubusercontent.com/85226895/181203350-ae182a4d-e141-43f7-b79c-373fb1c88669.png">

The truncated URL sometimes leads to 404 and sometimes to completely unrelated sites. Truncated url above for instance redirects to following url:

<img width="576" alt="image" src="https://user-images.githubusercontent.com/85226895/181203469-7c69e693-afd9-4279-bb3a-7ad68143e820.png">

**Additional context**
The redirect mechanism of TinyURL might be a potential security issue as users can't verify the domain/url they want to follow through directly. TinyURL might also be a blocked by some orgs sec policies due to this. Although not the prettiest, outputting the full URL is safer.

**Comment by a13zen** [comment]
An additional issue with using TinyURL  is if you have a lot of modules failing concurrently, you hit their rate limits:

```bash
File ".venv/lib/python3.9/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tinyurl.com', port=80): Max retries exceeded with url: /api-create.php?url=https%3A%2F%2Feu-west-1.console.aws.amazon.com%<redacted> (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x1040652e0>, 'Connection to tinyurl.com timed out. (connect timeout=2)'))
```

**Comment by dgraeber** [comment]
unfortunately, using a table truncates the url.  I will remove the tinyurl and the table and just print the url in plaintext
