### ISSUE TITLE
[FEATURE] files.pythonhosted.org read timeout issue when deploy seedfarmer in AWS China regions

### ISSUE THREAD

**Issue by danxie1999** [awslabs/seed-farmer#553]
**Describe the bug**
When we deploy seedfarmer in AWS China regions, seedfarmer (codeseeder) is injecting this code fragment below before our own deployspec.yaml / buildspec.yaml.

pip install aws-codeseeder~={__version__}

In China regions, normally, we will add a PIP mirror to work around the China internet issue. However, the seedfarmer is injecting pip code before our deployspec.yaml / buildspec.yaml file which lead to the files.pythonhosted.org read timeout issue when pip install the aws-codeseeder.

**To Reproduce**
1. Deploy in seedfarmer in AWS China regions.
2. Most time, it would fail in build stage.

**Expected behavior**
Seedfarmer would deploy without issue in China regions.

**Screenshots**
<img width="1052" alt="image001" src="https://github.com/awslabs/seed-farmer/assets/28647452/5ddd7427-c718-4ff8-8b7b-8cf6e7ed22fc">

**Additional context**
Potential fix:
### modify file .venv/lib/python3.9/site-packages/aws_codeseeder/services/codebuild.py(line 324) install section to below
Before Change:
install = [
    "mv $CODEBUILD_SRC_DIR/bundle/retrieve_docker_creds.py /var/scripts/retrieve_docker_creds.py || true",
    "/var/scripts/retrieve_docker_creds.py && echo 'Docker logins successful' || echo 'Docker logins failed'",
]
 
After Change
install = [
    "if [[ \"${AWS_REGION}\" =~ ^cn-.* ]]; then\n  pip config set global.index-url\
        \ https://pypi.tuna.tsinghua.edu.cn/simple\n  npm config set registry\
        \ https://registry.npmmirror.com/\nfi\n",
    "mv $CODEBUILD_SRC_DIR/bundle/retrieve_docker_creds.py /var/scripts/retrieve_docker_creds.py || true",
    "/var/scripts/retrieve_docker_creds.py && echo 'Docker logins successful' || echo 'Docker logins failed'",
]

**Comment by JunjieTang-D1** [comment]
please review the proposed fix by @danxie1999

**Comment by dgraeber** [comment]
I changed this to a feature request as the ability to change the pip mirror is a feature that we don't currently support.

I will review options.
