### ISSUE TITLE
[FEATURE] Add option to destroy and redeploy module

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#554]
**Is your feature request related to a problem? Please describe.**
Id like to be able to test destroy of the specific module. When I am developing, in order to test if i set up destory phase correctly, i have to manipulate manifest twice (before destory and after destory to bring it back). 

**Describe the solution you'd like**
Id appreciate option to have something like seedfarmer cycle <MODULE NAME> which would destroy and deploy the specific module. This should only allow to do this if no other module depends on it. 

**Describe alternatives you've considered**
Commenting and uncommenting module in the manifest

**Comment by dgraeber** [comment]
@zaremb Are you only testing the destroy phase in the deployspec?  If so, are you leveraging the `seedfarmer store deployspec` CLI?

**Comment by zaremb** [comment]
No, how would it help me?

**Comment by dgraeber** [comment]
Assuming that you are using CDK, the CDK code will destroy (that is vetted by the AWS CDK team).  So what you are really testing is the  destroy portion of the deployspec (i would deduce).  We provided that command to allow developers to update the deployspec of a deployed module to test / vet the destroy portion of the spec.  If your module fails to fully destroy, you can update the spec and rerun the destroy command (w/o needing to redeploy).

**Comment by zaremb** [comment]
Okay. ill give it a go
