### ISSUE TITLE
[FEATURE] Make validation of manifests strict

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#560]
**Is your feature request related to a problem? Please describe.**
(Note: I am using SeedFarmer 3.2.2):

Ive seen that some form of validation is added in 3.4.

`Add schema validation step checking that either value or value_from is present for each parameter`

Thanks for that!
Can we go further than that? 
Every so often I see my modules failing, after inspecting codebuild env parameters I see that one parameter is missing. Then I will do inspection of yamls, to finally find that there is typo in parameter definition.  This sorts of error are often not covered by the validation above

**Describe the solution you'd like**
Validate if manifests are correct (strictly). SeedFarmer expects manifests to look in a certain way. If that is not the case, fail with validation error instead of proceeding to deploy.
What I mean by that is that for manifests, please check if there are **only** fields that are expected. So i.e. 
```
name: MY_BUCKET 
    valueFrom:
      mduleMetadata:
        group: a
        name: b
        key: c
```
or 
```
    valueFrom:
      parameter: abc
```
should fail on validation level and not get to the deployment phase

**Comment by zaremb** [comment]
Suggestion. To make it backwards compatible, you could add a flag like `strictManifestValidation` to seedfarmer.yaml.
If not present, it would continue behaving like it is right now

**Comment by dgraeber** [comment]
@zaremb I like that better than a flag.  We will investigate
