### ISSUE TITLE
[FEATURE] Support pipy private artifactory with authentication

### ISSUE THREAD

**Issue by danxie1999** [awslabs/seed-farmer#561]
**Is your feature request related to a problem? Please describe.**
In China regions, we usually utilize pipy China mirror like "https://pypi.tuna.tsinghua.edu.cn/simple" to overcome network issue. However, sometimes, we would like to use a private Artifactory to private pipy mirror. 

**Describe the solution you'd like**
name: testing
path: modules/dummy/blank
targetAccount: primary
targetRegion: cn-north-1
pypiMirror: https://{ARTIFACTORY_PYPI}
pypiMirrorConfig:
 ARTIFACTORY_USERNAME: {ARTIFACTORY_USERNAME}
 ARTIFACTORY_TOKEN:
      valueFrom:
        envVariable: ARTIFACTORY_TOKEN
parameters:
  - name: encryption-type
    value: SSE
  - name: retention-type
value: DESTROY

**Describe alternatives you've considered**
For now, we could config in the module deployspec file:
pip config set global.index-url https://${ARTIFACTORY_USERNAME}:${ARTIFACTORY_TOKEN}@${ARTIFACTORY_PYPI}

**Additional context**

**Comment by dgraeber** [comment]
We will review how this can be implemented via CodeSeeder and SecretsManager
