### ISSUE TITLE
[FEATURE] Switch default codebuild build image

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#568]
**Is your feature request related to a problem? Please describe.**
The default Standard build image currently used by seedfarmer contains many old and deprecated runtimes.

Switch the default to use the newer `codebuildImage: aws/codebuild/standard:7.0`.

**Comment by dgraeber** [comment]
This managed by AWS-Codeseeder.  We have updated and released codeseeder with this update (`aws-codeseeder==0.12.1`).  You will need to update to this version and then update the seedkit in each account/region:
After updating aws-codeseeder you can either:
1. run `seedfarmer apply <manifests> --update-seedkit` (only once in all deployments)
2. run `codeseeder deploy seedkit <project>` with a session in each account / region

**Comment by dgraeber** [comment]
Closing as this is addressed
