### ISSUE TITLE
[FEATURE] Mirror urls support from environment variable or AWS SSM parameter store

### ISSUE THREAD

**Issue by danxie1999** [awslabs/seed-farmer#569]
**Is your feature request related to a problem? Please describe.**
This is related the feature request: https://github.com/awslabs/aws-codeseeder/issues/149
Now the seed-farmer supports npm and pypi mirrors which was great. However, the mirror url has to be hardcoded in the deployment build spec file, can not be loaded from environment variable or SSM parameter store. 

**Describe the solution you'd like**
It would be great if the mirrors url could be loaded from environment variable or SSM parameter store.  
**Describe alternatives you've considered**
name: testing
path: modules/dummy/blank
targetAccount: primary
targetRegion: cn-north-1
npmMirror: 
    valueFrom:
        envVariable: NPM_MIRROR_URL
pypiMirror: 
    valueFrom:
        parameterValue: pypimirror

**Additional context**

**Comment by dgraeber** [comment]
@danxie1999 The envVariable is really only for parameters.  But, we are currently testing support for environment replace for all values in a manifest. This is still exploratory, but with the feature we are currently testing, you can wrap a string that is a value with `${ }` and if the env variable set, then it would be replaced.  For example:
```
name: testing
path: modules/dummy/blank
targetAccount: primary
targetRegion: cn-north-1
npmMirror: ${NPM_MIRROR_URL}
pypiMirror: ${PYPI_MIRROR_URL}
```

If NPM_MIRROR_URL and PYPI_MIRROR_URL are set, then they would be dynamically replaced (ex. passing in `--env-file` ) when the template is resolved.

Please take a look at 3.5.0rc2 (https://pypi.org/project/seed-farmer/#history) and try it out (NOTE: it is a release candidate and is in process of being released if effective)

**Comment by dgraeber** [comment]
@danxie1999 Please use `seed-farmer==3.5.0rc3` that I just pushed up to address a global parameter resolution issue

**Comment by danxie1999** [comment]
THX for your help, will give it a try~
