### ISSUE TITLE
[FEATURE] Specify which manifest is failing to be parsed

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#581]
**Is your feature request related to a problem? Please describe.**
Seedfarmer reports that it cannot parse manifest. But it does not say which one.
<img width="1082" alt="Screenshot 2024-05-14 at 10 26 08" src="https://github.com/awslabs/seed-farmer/assets/18630245/eddce54a-dad7-40e4-b5cc-25fb91d58742">
**Describe the solution you'd like**
Id like seedfarmer to tell me which file it cannot parse

**Comment by zaremb** [comment]
Note: I am using seedfarmer version 3.2.2.

**Comment by zaremb** [comment]
Note: I am aware if that if i read the full trace path will be printed at some point, but this is not user friendly. In my opinion, it should be printed at the end, so instead of
seedfarmer.errors.seedfarmer_errors.InvalidPathError: Cannot parse manifest file path
id like:
seedfarmer.errors.seedfarmer_errors.InvalidPathError: Cannot parse manifest file path at foo/bar.yaml

**Comment by dgraeber** [comment]
I will take a look
