### ISSUE TITLE
[FEATURE] Localstack to tack

### ISSUE THREAD

**Issue by koljahuang** [awslabs/seed-farmer#584]
Integrate localstack with seed-farmer 

Related background as below:
[Add any other context or screenshots about the feature request here.](https://github.com/awslabs/seed-farmer/pull/580)
[Add any other context or screenshots about the feature request here.](https://github.com/awslabs/seed-farmer/pull/578)

**Comment by dgraeber** [comment]
@koljahuang We have looked at this and we will not be supporting LocalStack in the immediate future:
1. the ability to override the endpoint in the session manager has a potential of bypassing SF security posture
2. we would not be able to support the calls to SF from inside a codebuild runtime and override the endpoint
