### ISSUE TITLE
[FEATURE] Support moving modules to different groups

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#586]
**Is your feature request related to a problem? Please describe.**
I need to move one module (lets call it module A) to a different group (due to dependencies it has to be deployed before other module). Now I have a problem, because there also exists module B, that depends on module A. If I move module A to a different group, seedfarmer thinks that module A should get destroyed, so it stops deployment because module B depends on it.

There are 2 problems:
1. Module A should not be destroyed, it just gets moved to a different location
2. Module B should not prevent moving of Module A to a different group

**Describe the solution you'd like**
Id like seedfarmer to understand that its the same module, so no destruction should happen.

**Describe alternatives you've considered**
Renaming module B, which will cause destruction and recreation of module B

**Additional context**
In my case there is only one module B, but lets imagine we have more modules that depend on A. This chain can grow big. Destruction of all of them just because i moved one module (without change of source code yet) will be very problematic

**Comment by dgraeber** [comment]
Thanks for this request.

This is not something we envision supporting.
In the context of a deployment, all modules in that deployment represent a proper ordering (the groups).  The name that is generated (<deployment>-<group>-<module>) for a module that is deployed can be represented once and only once.  To change the group a module sits in means a new concrete implementation of that module.  It is (to seedfarmer) an entirely unique module.

The dependency management we now have in place (based on customer requests and feedback) would then be violated as a module as represented by the name denoted above would no longer exist.

From a practical standpoint, there are a number of resources (module role, modulestack, metadata, etc.) that use that naming convention that cannot be altered after the module is deployed. 

_`Id like seedfarmer to understand that its the same module, so no destruction should happen.`_
In reality, it is not the same module as the name (the group) has changed.  The module may be based off of the same code, but it in fact is an entirely unique module in the deployment (to SeedFarmer).    There is no realistic way to change this other than changing the operating paradigm of SeedFarmer.
