### ISSUE TITLE
[FEATURE] Add --version command

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#59]
**Is your feature request related to a problem? Please describe.**
I'd like to quickly validate which version of seedfarmer I've got installed in my project.

**Describe the solution you'd like**
Add --version command flag to output current version from the version file. 

Optionally, add check to see if newer updates have been released and is available (should be semantic version aware)

**Describe alternatives you've considered**
Can run pip freeze to see package version.

**Comment by dgraeber** [comment]
This can be done

**Comment by dgraeber** [comment]
Added as a separate command for now:
> `seedfarmer version`

> seedfarmer 0.2.0.dev0
