### ISSUE TITLE
[FEATURE] Require explicit region

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#60]
**Is your feature request related to a problem? Please describe.**
Currently seedfarmer includes no contextual information on the AWS account or region it is targeting for deployments. This makes using the framework in a complex multi-region setup confusing and dangerous. 

**Describe the solution you'd like**
1. Always clearly output the AWS account being targeted for deployment
2. Require either explicitly specifying --region for the target region or check the availability of the AWS_REGION environment variable. Do not rely on the AWS_DEFAULT_REGION environment variable. 
3. Clearly display the target region for deployment
4. Optional but strongly recommended: prompt for confirmation (see below)

**Describe alternatives you've considered**
Alternatively, we could always prompt for confirmation before running an apply, similar to CDK. This is a good safety mechanism to ensure users are targeting their desired account, region and changes. 

This behavior can be bypassed with an automation flag e.g `--auto-confirm-apply`

**Additional context**
We are currently using two regions for testing and building on the framework. One region is for development and another for stable production releases. It is very simple for a developer to deploy to the wrong region as there is no confirmation prompt or info displayed by seedfarmer.

**Comment by dgraeber** [comment]
This will most likely be taken care of in the multi-account solution
