### ISSUE TITLE
[BUG] Update Jinja Dependency

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#603]
**Describe the bug**
Current Jinja dependency is being flagged as containing vuln. 
https://data.safetycli.com/v/70612/97c/

*** Recommendation ***
Add https://pypi.org/project/safety/ dependency vuln checker as CI job.

**Comment by a13zen** [comment]
After digging deeper. Looks like release from Jinja addressing issue is still pending....

**Comment by dgraeber** [comment]
This is not a bug as we cannot update Jinja - but we will review a scan on CI

**Comment by dgraeber** [comment]
@LeonLuttenberger lets huddle and come up with a path forward
