### ISSUE TITLE
[BUG] Bootstrap toolchain allows no trusted principals

### ISSUE THREAD

**Issue by dgraeber** [awslabs/seed-farmer#604]
The CLI command `seedfarmer bootstrap toolchain` allows the user to not pass in a trusted principal ARN, causing the toolchain template to fail.  There should be a trusted-principal ARN that is valid as a required field when making this call.

**Comment by dgraeber** [comment]
This validation should occur in the `seed-farmer/seedfarmer/commands/_bootstrap_commands.py::bootstrap_toolchain_account` to be sure that the ARN is a valid format.  There are times where this command is called w/o a principal passed in b/c the toolchain role is created and unchnaged, but the deployment role needs to be deployed (and the user is using the `--as-target` flag)

**Comment by kenerwin88** [comment]
Just hit this issue, I don't think you would ever call it w/o needing a principal?

**Comment by malachi-constant** [comment]
I would lean towards requiring the user to specifying the principal on every call to `bootstrap`, but I'll take a look and implement validation.

**Comment by malachi-constant** [comment]
Added a proposed change @dgraeber above, lmk your thoughts.
