### ISSUE TITLE
[BUG]Cache from out file

### ISSUE THREAD

**Issue by jinxiao** [awslabs/seed-farmer#624]
**Describe the bug**

When We tried to deploy seedfarmer modules from local, we always must delete the SeedFarmer cache otherwise it tries to deploy the wrong code: 

```
rm -rf codeseeder.out
```
 
If this not be done, seedfarmer will use the old code to deploy.
**To Reproduce**
1. Use one revision to deploy
2. Update to another revision.
3. re-deploy.
4. Without deleting codeseeder.out, it will use the previous revision.

**Expected behavior**
We expect to use the newest revision each time.

**Comment by dgraeber** [comment]
@jinxiao Thanks for this Issue request.  This is managed by AWS-Codeseeder, and I see your[ issue logged there](https://github.com/awslabs/aws-codeseeder/issues/195) also.

We will investigate.

**Comment by dgraeber** [comment]
@jinxiao Can you please elaborate on: "Update to another version"?  
Are you using the gitpath in your manifest, then changing the version?  For example:
`path: git::https://github.com/awslabs/idf-modules.git//modules/dummy/blank?ref=release/1.2.0` and updating to:
`path: git::https://github.com/awslabs/idf-modules.git//modules/dummy/blank?ref=release/1.3.0`

Or are you using local file paths and updating the local code:
`path: modules/dummy/blank' 


Looking at the code, we are overwriting the codeseeder.out directory every time, so I am trying to reproduce your error.

**Comment by dgraeber** [comment]
All correspondence for this related issue will be logged [HERE](https://github.com/awslabs/aws-codeseeder/issues/195) as this is not a SeedFarmer issue directly.  Leaving this issue open until resolved for reference

**Comment by dgraeber** [comment]
Closing as root-cause is not Seed-Farmer related
