### ISSUE TITLE
[FEATURE] Possibility to provide custom branch for templates

### ISSUE THREAD

**Issue by luisosses** [awslabs/seed-farmer#665]
**Is your feature request related to a problem? Please describe.**
As of this moment seedfarmer will accept template URLs where the templates live in the main/default branch of the repository. With this we are limiting the capacity of having dedicated branches for multiple templates within a single repository. 

**Describe the solution you'd like**
As we already provide the `--template-url` parameter, adding a `--template-branch` (which if is not specified the tool will have `main` as default value). This extra option will be used for the commands `seedfarmer init project` and `seedfarmer init module` 

**Describe alternatives you've considered**
Looking at the code, the only alternative we have is adding this parameter, otherwise is already hardcoded to use branches available only in this (seedfarmer) repository.

**Additional context**
I can proceed to prepare this functionality and submit a Pull Request for your evaluation.

**Comment by dgraeber** [comment]
@luisosses I think I understand what you are requesting:  If you have a different git repo (other than seed-farmer repo) that you want to use, you can specify that repo.  AND...you want to add the ability to change and use a branch in that repo for the init.

I want to confirm with you he use case and also assure that we cannot provide any cookiecutter validation for any branches outside of the ones that SF provides for init.

**Comment by luisosses** [comment]
Hello @dgraeber that's correct!

In the same way we are providing the possibility already of using a different repo with the `--template-url` parameter without any cookiecutter validation, but extending the functionality to be able to provide a branch.

The specific use case would be a single repository dedicated  or providing different templates in different branches (e.g. different IaC tools based templates for modules) - instead of needing a fully exclusive repository for a single template (which somehow we are "forcing" at the moment).

Let me know if I need to add something in the PR #666 

Thanks!
