### ISSUE TITLE
[FEATURE] NPM mirror support with Token

### ISSUE THREAD

**Issue by dgraeber** [awslabs/seed-farmer#671]
SeedFarmer currently has NPM mirror support, but there is no means to authenticate. 

We did implement pypi support with auth and the SecretsManager can be reused to support populating an .npmrc

This is to support use of our generic modules by customers that must leverage a mirror

**Comment by malachi-constant** [comment]
Will start on this, @dgraeber get in touch if there's anything else you'd like me know before implementation.
