### ISSUE TITLE
[BUG] SSM parameter changes not detected on redeploy

### ISSUE THREAD

**Issue by dgraeber** [awslabs/seed-farmer#674]
This is coming from #664 indicating that changes to SSM parameters are not detected forcing a redeploy.

This issue / bug is created to test and validate if this is correct.

To reproduce / test:
1. create an SSM parameter for a deployment to reference
2. add a SSM valueFrom parameter to a module manifest
3. deploy the module
4. change the SSM parameter
5. redeploy and confirm / deny that the module did deploy again (indicating a detected change)

**Comment by dgraeber** [comment]
The SeedFarmer team will review

**Comment by malachi-constant** [comment]
Will investigate.

**Comment by malachi-constant** [comment]
My testing does not yield any issues with detection of SSM parameter changes. 

Changes to parameters force redeploy as expected on `seedfarmer==4.0.4`
