### ISSUE TITLE
[BUG] Seedfarmer 4.0.4 doesn't cache information on AWS if it was provided as environment variables

### ISSUE THREAD

**Issue by ktulhax** [awslabs/seed-farmer#718]
**Describe the bug**

The following error occurs in case if module that uses environment variable was deleted and enviroment variable was unset

`seedfarmer.errors.seedfarmer_errors.InvalidManifestError: The environment variable (TEST_VARIABLE) is not available`

**To Reproduce**
1. Have project with the only one module that uses environment variable `TEST_VARIABLE`
2. `export TEST_VARIABLE="some_value"`
3. Create inital deployment with `seedfarmer apply`
4. `unset TEST_VARIABLE` and delete the module from yaml
5. Do `seedfarmer apply` again
6. See the error descibed above

**Expected behavior**
It was expected that seedfarmer will remember the values of yaml parameters on AWS if they were provided via environment variables

**Comment by malachi-constant** [comment]
In agreement here, not sure this behaviour should be changed unless there's some compelling use case that warrants it.
