### ISSUE TITLE
[BUG] disable dynamic environment variable replacement

### ISSUE THREAD

**Issue by swirkert1** [awslabs/seed-farmer#724]
**Describe the bug**
Seedfarmer replaces environement variables in manifests (see https://seed-farmer.readthedocs.io/en/stable/manifests.html#universal-environment-variable-replacement-in-manifests)

This leads to an error in case the manifest contains a script definition.

**To Reproduce**
Create an EKS nodegroup with preBootstrapCommands. E.g.:

        - eks_ng_name: ng-gdn412xlarge
          eks_node_quantity: 0
          eks_node_max_quantity: 30
          eks_node_min_quantity: 0
          eks_node_disk_size: 500
          eks_node_instance_type: "g4dn.12xlarge"
          use_gpu_ami: True
          eks_node_labels:
            usage: g4dn.12xlarge
            fast-disk-node: pv-nvme
          privateNetworking: true
          preBootstrapCommands:
            - |
              # Install NVMe CLI
              yum install nvme-cli -y
        
              # Get list of NVMe Drives
              nvme_drives=$(nvme list | grep "Amazon EC2 NVMe Instance Storage" | cut -d " " -f 1 || true)
              readarray -t nvme_drives <<< "$nvme_drives"
              'num_drives=1'
              # Install software RAID utility
              yum install mdadm -y
        
              # Create RAID-0 array across the instance store NVMe SSDs
             'mdadm --create /dev/md0 --level=0 --name=md0 --raid-devices=$num_drives "${nvme_drives[@]}"'
              # Format drive with Ext4
              mkfs.ext4 /dev/md0

              # Get RAID array's UUID
              uuid=$(blkid -o value -s UUID /dev/md0)
   
              # Create a filesystem path to mount the disk
              mount_location="/mnt/fast-disks/${uuid}"
              mkdir -p $mount_location
        
              # Mount RAID device
              mount /dev/md0 $mount_location
        
              # Have disk be mounted on reboot
              mdadm --detail --scan >> /etc/mdadm.conf 
              echo /dev/md0 $mount_location ext4 defaults,noatime 0 2 >> /etc/fstab

**Expected behavior**
The preBootstrapCommands are executed as is, seedfarmer does no magic behind the scenes.

**Screenshots**
Traceback (most recent call last):
  File "/home/q460462/.venvs/gymcicd/lib/python3.9/site-packages/seedfarmer/utils.py", line 206, in replace_str
    return value.replace("${" + match + "}", os.environ[match.strip()])
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'nvme_drives[@]'

**Comment by kukushking** [comment]
Hi @swirkert1 thank you for opening this. The team is evaluating the fix.
