### ISSUE TITLE
[BUG] Issue with extracting release archives in seedfarmer 5.0.0

### ISSUE THREAD

**Issue by jayanthmandavilli** [awslabs/seed-farmer#749]
**Describe the bug**
In the module manifest we are trying to use http archive as a dependency.

```
name: networking
path: archive::https://artifactory.com/artifactory/shared_module-1.0.0.zip/?module=infra/modules/shared_module
```

My archive(which is stored in artifactory) contains folder structure as below
infra/modules/
├── shared_module
│   ├── app.py
│   ├── deployspec.yaml
│   ├── requirements.in
│   ├── requirements.txt
│   ├── src/

So, when executing the seedfarmer apply, I'm getting below error

> raise seedfarmer.errors.InvalidPathError(f"No deployspec.yaml file found in module directory: {p}")
>seedfarmer.errors.seedfarmer_errors.InvalidPathError: No deployspec.yaml file found in module directory: /home/repo/seedfarmer.archive/_artifactory_shared_module-1.0.0/modules/shared_module/deployspec.yaml

Below is the folder structure after seedfarmer is extracting the archive.
Could see that all files are not extracted to modules/shared_module instead got extracted in the archive root.
seedfarmer.archive
└── _artifactory_shared_module-1.0.0
    ├── app.py
    ├── deployspec.yaml
    ├── pyproject.toml
    ├── README.md
    ├──modules
    │       └── shared_module
    ├── requirements.in
    ├── requirements.txt

**To Reproduce**
seedfarmer - 5.0.0
This can be reproduced when the modules folder contain only shared_module folder.
I'm not seeing the issue when there are multiple sub folders under the modules directory.

1. Update your manifest with archive path'
2. The archive zip should contain modules/<only_common_folder> and make sure it doesn't contain other folder inside the modules dir
3. execute seedfarmer apply

**Expected behavior**
Extracting the archive should preserve the folder structure

**Comment by dgraeber** [comment]
@jayanthmandavilli  Hi - thanks for your issue submission.

I think you are missing the `archive` designation in your path?  For example: I just tested with the following:
```path: archive::https://github.com/awslabs/idf-modules/archive/refs/tags/v1.13.0.zip?module=modules/dummy/blank```

You have provided the following:
```
name: networking
path: https://artifactory.com/artifactory/shared_module-1.0.0.zip/?module=infra/modules/shared_module
```

but I think you want the following:
```
name: networking
path: archive::https://artifactory.com/artifactory/shared_module-1.0.0.zip/?module=infra/modules/shared_module
```
Please confirm?

**Comment by jayanthmandavilli** [comment]
> @jayanthmandavilli Hi - thanks for your issue submission.
> 
> I think you are missing the `archive` designation in your path? For example: I just tested with the following: `path: archive::https://github.com/awslabs/idf-modules/archive/refs/tags/v1.13.0.zip?module=modules/dummy/blank`
> 
> You have provided the following:
> 
> ```
> name: networking
> path: https://artifactory.com/artifactory/shared_module-1.0.0.zip/?module=infra/modules/shared_module
> ```
> 
> but I think you want the following:
> 
> ```
> name: networking
> path: archive::https://artifactory.com/artifactory/shared_module-1.0.0.zip/?module=infra/modules/shared_module
> ```
> 
> Please confirm?

I'm sorry for the typo in my description and now I've corrected it, yes I've `archive` designation in my code already.

**Comment by dgraeber** [comment]
Ok..thanks for this.   I am not able to replicate the issue with the archives I have.  Can you compare your archive / zip to the one located at `https://github.com/awslabs/idf-modules/archive/refs/tags/v1.13.0.zip`

Though I don't disagree that this is a problem, I just cannot reproduce it in order to triage

**Comment by jayanthmandavilli** [comment]
the archive which you have shared contains more than one sub folder inside the modules,
modules/
 |---- testing
 |---- storage
 |---- network.

In my case, modules folder contains only one sub folder
modules/
 |---- network

**Comment by dgraeber** [comment]
Just to confirm, your archive looks like this:

infra/
|---- modules/
|----|----- network


?

**Comment by jayanthmandavilli** [comment]
yes

**Comment by dgraeber** [comment]
I will have to take a look after the US holiday

**Comment by jayanthmandavilli** [comment]
the issue is possibly caused by line 79 and 100 in `https://github.com/awslabs/seed-farmer/blob/main/seedfarmer/mgmt/archive_support.py`  and removing the module and using root level archive is possible cause to line 116

**Comment by dgraeber** [comment]
@jayanthmandavilli 
I have pushed a patch release (5.0.1) after testing with an archive that matches your description and with multiple other variations and have had successful results (where the archive is extracted as-is and the relative path of the module is unchanged).  Please try that version?

**Comment by dgraeber** [comment]
@jayanthmandavilli 
Version 5.0.1 has been yanked.  This broke the backward compatibility with the other archives.

The recommendation is to change your manifest path from:

```
> name: networking
> path: archive::https://artifactory.com/artifactory/shared_module-1.0.0.zip/?module=infra/modules/shared_module
```
to 
```
name: networking
path: archive::https://artifactory.com/artifactory/shared_module-1.0.0.zip/?module=modules/shared_module
```

I could not replicate the issue in which the archive did not extract to the proper location

**Comment by dgraeber** [comment]
Reopening this issue for communication

**Comment by jayanthmandavilli** [comment]
@dgraeber , thanks for the communication

**Comment by smarkus577** [comment]
@dgraeber 
How about the idea of making the `module` parameter optional?
In the case of nested folders, the old implementation would unpack the zip and moves all files of the module to the root directory. 
This means the deployspec.yaml is at the root of the unpacked module and we don't need to specify a path anymore

**Comment by dgraeber** [comment]
@smarkus577 I am not sure I agree with that recommendation.  
BACKGROUND: the archives are designed to be structured like a SeedFarmer project, where you have a root dir (the project) and the supporting dirs nested and accessed via relative paths (modules, manifests, etc).  Using the dir names `modules` or `manifests` or `datafiles` is just a semantic, and not required (you can name them whatever you want) as long as you reference that name. 

I disagree with your suggestion for two reasons:

1. it violates the design (more importantly it would remove a standard)
2. It masks the real problem

Item 2 is what I want to focus on.  I have not been able to replicate the issue (multiple configuration of the archive to match was was described in this issue and numerous variations pulled from S3 over HTTPS and from GitReleases).  I cannot seem to reproduce the issue.

This is where I suggest we focus.

**Comment by jayanthmandavilli** [comment]
> to

> name: networking
> path: archive::https://artifactory.com/artifactory/shared_module-1.0.0.zip/?module=modules/shared_module

> I could not replicate the issue in which the archive did not extract to the proper location

Hi @dgraeber, we did try above approach as well, but the modules are downloading directly in the parent folder of archive(_artifactory_shared_modules-1.0.0) instead of _artifactory_shared_modules-1.0.0/modules/shared_module.
But seedfarmer throwing below error 
No deployspec.yaml file found in module directory:  /home/jayanth/repo/seedfarmer.archive/_artifactory_shared_modules-1.0.0/modules/shared_module/deployspec.yaml

I even tried just giving only shared_module
> name: networking
> path: archive::https://artifactory.com/artifactory/shared_module-1.0.0.zip/?module=shared_module

This one also having the same issue and seedfarmer is throwing below error
No deployspec.yaml file found in module directory: /home/jayanth/repo/seedfarmer.archive/_artifactory_shared_modules-1.0.0/shared_module/deployspec.yaml

Which means the zip contains only modules with only one sub folder, it is unziping in the parent directory.

**Comment by dgraeber** [comment]
@jayanthmandavilli 
Email me directly at dgraeber@amazon.com   ?
