### ISSUE TITLE
[BUG] Importing of `seedfarmer` checks and requires a root level seedfarmer.yaml file

### ISSUE THREAD

**Issue by chamcca** [awslabs/seed-farmer#79]

**Comment by dgraeber** [comment]
Things of note: the `__Init__.py` of seedfarmer has the decorator annotations for codeseeder, which requires a PROJECT name.  We will have to find a way to move the call to find seedfarmer.yaml and the config for codeseeder to a location where it is not invoked when seedfarmer is imported, but is invoked every where else (pretty much)
